# Generated by Django 4.2.3 on 2023-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
