# Generated by Django 4.2.5 on 2023-09-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category',), 'verbose_name_plural': 'categories'},
        ),
    ]
